### ISSUE TITLE
Our names and emails in setup.py

### ISSUE THREAD

**Issue by PabRod** [gossips/earlywarningsignals#2]
The file `setup.py` should contain information about the author(s) of the code. Right now, it doesn't.

## Suggested action

Add at least one email and one name in the file. The url is also wrong, update it to the current repository.

**Comment by ingridleemput** [comment]
Done!

**Comment by PabRod** [comment]
Solved in commit 9e1cc96403bc44843c2c42d576b7d80966635889

**Comment by PabRod** [comment]
Right now, only Ingrid's name is on the list. Let's add, at least, the names of the four people that were in today's meeting.

- Els
- Usman
- Pablo

**Comment by PabRod** [comment]
Closed by #8
